Add operationIds for OpenAPI specification
openhab/openhab-core pull request #1861
Opened 2020-11-29 14:00 UTC by hoffe86

Hey
I prepared a pull request, which add the operationId to our OpenAPI spec to improve the generation of clients,
For example tools like [autotest](https://github.com/Azure/AutoRest) is using the OperationId as function name for the client class or low code tools like Microsoft Power Apps using the OperationId to create API facade to consume the API with their editors.

Let me know when I need to rename one or more operationId, when the name does not fit the functionality

2020-11-30 09:39 UTC, wborn requested changes
In general it looks good to me. Though it would be nice if you fix the typos and make it a bit more consistent.

2020-11-30 09:39 UTC, wborn commented on bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/discovery/InboxResource.java
> +    @Operation(operationId = "aproveInboxItemById", summary = "Approves the discovery result by adding the thing to the registry.", responses = {
```suggestion
    @Operation(operationId = "approveInboxItemById", summary = "Approves the discovery result by adding the thing to the registry.", responses = {
```

2020-11-30 09:39 UTC, wborn commented on bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
> +    @Operation(operationId = "removeMemberToGroupItem", summary = "Removes an existing member from a group item.", security = {
```suggestion
    @Operation(operationId = "removeMemberFromGroupItem", summary = "Removes an existing member from a group item.", security = {
```

2020-11-30 09:39 UTC, wborn commented on bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
> +    @Operation(operationId =  "addsOrUpdatesItemsInRegistry", summary = "Adds a list of items to the registry or updates the existing items.", security = {
```suggestion
    @Operation(operationId =  "addOrUpdateItemsInRegistry", summary = "Adds a list of items to the registry or updates the existing items.", security = {
```

2020-11-30 09:39 UTC, wborn commented on bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java
> +    @Operation(operationId = "linksItemToChannel", summary = "Links item to a channel.", security = {
```suggestion
    @Operation(operationId = "linkItemToChannel", summary = "Links item to a channel.", security = {
```

2020-11-30 09:39 UTC, wborn commented on bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
> +    @Operation(operationId = "CreateThingInRegistry", summary = "Creates a new thing and adds it to the registry.", security = {
```suggestion
    @Operation(operationId = "createThingInRegistry", summary = "Creates a new thing and adds it to the registry.", security = {
```

2020-11-30 09:39 UTC, wborn commented on bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
> +    @Operation(operationId = "GetThings", summary = "Get all available things.", responses = {
```suggestion
    @Operation(operationId = "getThings", summary = "Get all available things.", responses = {
```

2020-11-30 09:39 UTC, wborn commented on bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
> +    @Operation(operationId = "GetThingById", summary = "Gets thing by UID.", security = {
```suggestion
    @Operation(operationId = "getThingById", summary = "Gets thing by UID.", security = {
```

2020-11-30 09:39 UTC, wborn commented on bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
> +    @Operation(operationId = "getAvailableForThing", summary = "Get all available firmwares for provided thing UID", security = {
```suggestion
    @Operation(operationId = "getAvailableFirmwaresForThing", summary = "Get all available firmwares for provided thing UID", security = {
```

2020-11-30 09:39 UTC, wborn commented on bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java
> +    @Operation(operationId = "getSitemapsByName", summary = "Get sitemap by name.", responses = {
```suggestion
    @Operation(operationId = "getSitemapByName", summary = "Get sitemap by name.", responses = {
```

2020-11-30 09:39 UTC, wborn commented on bundles/org.openhab.core.io.rest.ui/src/main/java/org/openhab/core/io/rest/ui/internal/UIResource.java
> +    @Operation(operationId = "getRegisterUIComponentsInNamespace", summary = "Get all registered UI components in the specified namespace.", responses = {
```suggestion
    @Operation(operationId = "getRegisteredUIComponentsInNamespace", summary = "Get all registered UI components in the specified namespace.", responses = {
```

2020-11-30 09:39 UTC, wborn commented on bundles/org.openhab.core.io.rest.voice/src/main/java/org/openhab/core/io/rest/voice/internal/VoiceResource.java
> +    @Operation(operationId = "interpretTextByDefaultIntpreter", summary = "Sends a text to the default human language interpreter.", responses = {
```suggestion
    @Operation(operationId = "interpretTextByDefaultInterpreter", summary = "Sends a text to the default human language interpreter.", responses = {
```

2020-11-30 19:03 UTC, hoffe86 commented
Hey @wborn 
I added your suggestions.
Sorry for the messy PR, there was additional signoff required :-(

2020-12-02 09:11 UTC, silamon commented
If you don't mind, a little help to get the build green: 
* In TokenResource, there's a "(" added by accident
* In VoiceResource, you've changed a "}" to "g"
* Run mvn spotless:apply in the root folder to add or remove missing spaces where needed

2020-12-02 11:05 UTC, wborn requested changes
Thanks for addressing my comments!

Looks like the `operationId` is still missing on the `getApiTokens` and `removeApiToken` operations in the `TokenResource`. Can you also add it to those operations?

Will you also create a PR to add these `operationId`s to the `@Operation`s in openhab-webui?

Can you also squash all these commits into one?

2020-12-07 20:43 UTC, hoffe86 commented
Added the missing operation ids and reverted the changes for gitignore file.
@wborn  Yes I will also taking care on the operation ids in webui package

2020-12-10 22:11 UTC, wborn approved these changes
Thanks for adding all the IDs! :+1:

2020-12-10 22:12 UTC, merged