[config] Added config validator for parameter options
openhab/openhab-core pull request #2691
Opened 2022-01-16 14:00 UTC by cweitkamp

- Added config validator for parameter options

Depends on #2690 

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

2022-02-01 07:17 UTC, J-N-K commented on bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/OptionsValidator.java
> +        if (!param.getOptions().stream().map(o -> o.getValue()).anyMatch(v -> v.equals(value.toString()))) {
Use `noneMatch`

2022-02-01 07:17 UTC, J-N-K commented on bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/OptionsValidator.java
> +            return new ConfigValidationMessage(param.getName(), messageKey.defaultMessage, messageKey.key);
It would be nice to add the list of allowed options here. This might be helpful to correct the setting.

2022-02-07 15:28 UTC, J-N-K requested changes
A general comment: IMO `ConfigDescriptionParameterValidatorFactory` should be removed. There is no need for it, it just returns a new instance which could also be achieved by inserting `new ...` in the map. But maybe we should put that in another PR (like removing the unnecessary checks we talked about in #2690.

2022-02-08 13:45 UTC, J-N-K approved these changes

2022-02-09 08:00 UTC, wborn approved these changes
Thanks for adding the validator!

2022-02-09 08:00 UTC, merged