[Voice] stop ks while stt and fixes
openhab/openhab-core pull request #2809
Opened 2022-02-27 15:17 UTC by GiviMAD

Signed-off-by: Miguel Álvarez Díez <miguelwork92@gmail.com>

This pr contains:

* stop ks while stt in dialog processor (we were already ignoring ks events)
* fix language check for services involved in dialog
* fix the "best match" format resolution broken by my in a previous pr.

I'm able to use the audio capabilities again after this changes.

2022-02-27 15:18 UTC, GiviMAD commented
@lolodomo, in case you were trying to test the changes to the Pulseaudio binding, dialog processing was not working before this changes

2022-02-27 15:33 UTC, lolodomo requested changes

2022-02-27 15:33 UTC, lolodomo commented on bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
> +            AudioFormat sttAudioFormat = getBestMatch(sttAudioFormats, sink.getSupportedFormats());
Mismatch STT and TTS. Maybe this just the variable names which are wrong?

2022-02-27 16:13 UTC, lolodomo approved these changes
LGTM

2022-02-27 16:15 UTC, lolodomo commented
A test is now no more working.

2022-02-27 16:33 UTC, GiviMAD commented
> A voice integration test is now no more working.

I will check it

2022-02-27 16:43 UTC, GiviMAD commented
I'm not able to run those tests locally.
Do you know were I can find the tests logs to check what is happening?

2022-02-27 16:51 UTC, lolodomo commented
Maybe the new restart of KS is a problem for the current itests.

2022-02-27 16:53 UTC, lolodomo commented
Maybe you could create a separate PR just for broken format best match, especially if the full feature is now broken. If true, we need a very fast merge.

2022-02-27 17:04 UTC, GiviMAD commented
ok I will undo those changes

2022-02-27 17:12 UTC, GiviMAD commented
I have reverted instead the ks stop and will open a separate us for it, let's see if the tests past and I will rename the pr

2022-02-27 17:15 UTC, lolodomo commented
Let see if it compiles. 
But then please fix again the typo sttAudioFormat vs ttsAudioFormat

2022-02-27 17:17 UTC, lolodomo commented
Another possible reason for failing tests could also be your new check about locales.

2022-02-27 17:34 UTC, GiviMAD commented
> But then please fix again the typo sttAudioFormat vs ttsAudioFormat

That's included in this one I just removed the stop ks changes.
PR renamed!

2022-02-27 17:49 UTC, lolodomo requested changes

2022-02-27 17:49 UTC, lolodomo commented on bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
> +            AudioFormat sttAudioFormat = getBestMatch(ttsAudioFormats, sink.getSupportedFormats());
ttsAudioFormat rather than sttAudioFormat

2022-02-27 17:56 UTC, lolodomo commented
@GiviMAD : please slow down and read carefully the comments. You are naming your variables with "stt" while they should be named with "tts" as we are in the method "say".

2022-02-27 17:58 UTC, lolodomo approved these changes
LGTM

2022-02-27 17:59 UTC, lolodomo commented
Thank you @GiviMAD 

@wborn or @cweitkamp  or @kaikreuzer : please merge this PR quickly

2022-02-27 17:59 UTC, lolodomo commented
Fix #2808

2022-02-27 22:45 UTC, GiviMAD commented
@lolodomo can you trigger this one again? the errors seems no related to the changes

2022-02-27 22:59 UTC, lolodomo commented
Sorry I can't, I have no rights on this repo.

2022-02-28 08:10 UTC, wborn approved these changes
Thanks for the fix!

2022-02-28 08:10 UTC, merged

2022-02-28 08:12 UTC, wborn commented
I have triggered a build so @t2000 can test the fix. :slightly_smiling_face:

2022-02-28 15:39 UTC, t2000 commented
@wborn Thanks for pinging me. I have just locally tested it in my IDE with the latest `main` branch and I can confirm that I am now able again to play picoTTS outut on my squeezebox sinks.

@GiviMAD Thanks for fixing it! And no worries about having made a mistake! If one doesn't contribute one cannot make mistakes ;-) So please stay motivated to contribute (and potentially create new bugs), because that's the only way openHAB can grow.