[Semantics] Return parent Location and Equipment
openhab/openhab-core pull request #2928
Opened 2022-04-23 02:53 UTC by jimtng

Resolve #2924 

Instead of returning the given item, getEquipment() and getLocation() returns the item's parent Equipment / Location. This allows the caller to navigate the hierarchy, e.g. get the parent location of the given location.

2022-04-23 14:51 UTC, jlaur requested changes
Nice! Two minor comments for the tests.

2022-04-23 14:51 UTC, jlaur commented on bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/actions/SemanticsTest.java
> +        assertNull(Semantics.getLocation(indoorLocationItem));
For consistency with the constraint-based Assert model:
```suggestion
        assertThat(Semantics.getLocation(indoorLocationItem), is(nullValue()));
```

2022-04-23 14:51 UTC, jlaur commented on bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/actions/SemanticsTest.java
> +        assertNull(Semantics.getEquipment(equipmentItem));
```suggestion
        assertThat(Semantics.getEquipment(equipmentItem), is(nullValue()));
```

2022-04-23 20:56 UTC, jimtng commented
@jlaur thanks for your review. I have changed the assertion as suggested. I'm not sure about the spacing in-between lines and why they are that way, but I added spacing to make them all spaced the same way.

2022-04-24 12:59 UTC, wborn approved these changes
Thanks! It looks good to me, but it would be nice if @cweitkamp can also have a quick look.

2022-04-25 11:04 UTC, cweitkamp approved these changes
LGTM. Thanks.

It sounds reasonable to change the logic.

2022-04-25 11:04 UTC, merged