Add event information for time triggers
openhab/openhab-core pull request #2965
Opened 2022-05-15 13:32 UTC by J-N-K

Closes #1391 

This creates event information for time-based triggers (DateTimeTrigger, GenericCronTrigger, TimeOfDayTrigger). The topic contains the trigger type, the trigger id (or label) is passed as source and the trigger configuration as payload of the event. 

Signed-off-by: Jan N. Klug <github@klug.nrw>

2022-10-05 22:28 UTC, ccutrer commented
+1. This enhancement would allow the jrubyscripting helper gem (https://github.com/boc-tothefuture/openhab-jruby/) to remove its own CronTrigger type that's used simply to correlate which trigger triggered the rule.

2022-10-05 22:28 UTC, ccutrer commented
cc @boc-tothefuture

2022-11-05 08:00 UTC, J-N-K commented
What would be the "payload" of these events?

2022-11-07 18:03 UTC, rkoshak commented
Even if it's just a boolean flag that would be sufficient. Or maybe a new field could be added to `event` that is always there and has an enum indicating how the rule was triggered. I like that idea because it means we don't need to figure it out based on what's `undefined` and instead we could just check.

    if(this.event.triggeredBy = 'Time')
    if(this.event.triggeredBy = 'Manual')
    if(this.event.triggeredBy = 'CalledBy') // could carry an additional parameter with the UID of the rule that called it
    if(this.event.triggeredBy = 'ItemUpdate')
    if(this.event.triggeredBy = 'ItemCommand')

and so on.

2022-11-07 18:30 UTC, ccutrer commented
at the lowest level, _anything_ would be sufficient, so that the trigger's module id is in the context map in some way that's sent to the action's execute method. ideal would be an "event" object, descended from AbstractEvent. I don't even care if it doesn't have extra fields (a calling rule UID would definitely be nice for the call-rule action).

2022-11-07 18:31 UTC, ccutrer commented
> Even if it's just a boolean flag that would be sufficient. Or maybe a new field could be added to `event` that is always there and has an enum indicating how the rule was triggered. I like that idea because it means we don't need to figure it out based on what's `undefined` and instead we could just check.
> 
> ```
> if(this.event.triggeredBy = 'Time')
> if(this.event.triggeredBy = 'Manual')
> if(this.event.triggeredBy = 'CalledBy') // could carry an additional parameter with the UID of the rule that called it
> if(this.event.triggeredBy = 'ItemUpdate')
> if(this.event.triggeredBy = 'ItemCommand')
> ```
> 
> and so on.

Assuming we get a distinct descendant of `AbstractEvent` for each possibility, you could just check the event's class type instead of having an explicit enum.

2022-11-07 18:49 UTC, J-N-K commented
`getType` should be available on all existing events. So what we need is an event for triggering manually/by other rule.

2022-11-27 13:31 UTC, J-N-K commented
In JS a rule with

```
console.log("received: '" + event + "' with payload '" + event.getPayload() + "'")
```

result in the following logs

- `received: 'Execution triggered by manual' of type 'ExecutionEvent' with payload '{}'` when triggered from UI
- `received: 'Execution triggered by runRuleAction' of type 'ExecutionEvent' with payload '{"previous":{"topic":"openhab/execution/2d4f245946/triggered","payload":"{}","source":"manual"}}'`when triggered from another rule that was triggered manually
- `received: 'Timer 1 triggered.' of type 'TimerEvent' with payload '{"cronExpression":"0 0/5 * * * ? *"}'` when triggered from a cron trigger

2023-04-29 17:04 UTC, LukasA83 commented
This feels really useful, can we get it merged?

2023-05-17 14:05 UTC, rkoshak commented
Ping @openhab/maintainers, this PR is awaited with great anticipation by me and others. It would be a great new feature to brag about for OH 4 if we can get it merged.

2023-05-27 20:11 UTC, kaikreuzer requested changes
Thanks, just one small bug to fix.

2023-05-27 20:11 UTC, kaikreuzer commented on bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/events/TimerEvent.java
> +     * constructs a new rule added event
```suggestion
     * Constructs a new rule added event
```

2023-05-27 20:11 UTC, kaikreuzer commented on bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandler.java
>              triggerHandlerCallback.triggered(module);
Shouldn't this line be removed?

2023-05-28 08:15 UTC, kaikreuzer approved these changes
Thanks!

2023-05-28 08:15 UTC, merged