Avoid parallel streams with common thread pool to avoid deadlocks
openhab/openhab-core pull request #3137
Opened 2022-10-30 11:16 UTC by ssalonen

To mitigate issue #3125

Signed-off-by: Sami Salonen <ssalonen@gmail.com>

2022-10-30 17:56 UTC, ssalonen commented
CI seems fail with expire tests 

```
[ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 45.028 s <<< FAILURE! - in org.openhab.core.internal.items.ExpireManagerTest
[ERROR] org.openhab.core.internal.items.ExpireManagerTest.testIgnoreCommandDoesNotExtendExpiryOnStateUpdate  Time elapsed: 3.029 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
eventPublisherMock.post(<any>);
-> at org.openhab.core.internal.items.ExpireManagerTest.testIgnoreCommandDoesNotExtendExpiryOnStateUpdate(ExpireManagerTest.java:234)
Actually, there were zero interactions with this mock.

	at org.openhab.core.internal.items.ExpireManagerTest.testIgnoreCommandDoesNotExtendExpiryOnStateUpdate(ExpireManagerTest.java:234)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ExpireManagerTest.testIgnoreCommandDoesNotExtendExpiryOnStateUpdate:234 
Wanted but not invoked:
eventPublisherMock.post(<any>);
-> at org.openhab.core.internal.items.ExpireManagerTest.testIgnoreCommandDoesNotExtendExpiryOnStateUpdate(ExpireManagerTest.java:234)
Actually, there were zero interactions with this mock.

[INFO] 
[ERROR] Tests run: 794, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[ERROR] There are test failures.
```

2022-11-01 08:18 UTC, J-N-K requested changes
Otherwise LGTM

2022-11-01 08:18 UTC, J-N-K commented on bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/AbstractLinkRegistry.java
> +                return commonItems;
```suggestion
                return !Collections.disjoint(forItemName, forLinkedUID);
```

2022-11-01 17:25 UTC, ssalonen commented on bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/AbstractLinkRegistry.java
> +                return commonItems;
https://github.com/openhab/openhab-core/pull/3137/commits/ec4fb5cefd20b4a5e8aecaa6e82e76edd15255ba

2022-11-01 17:26 UTC, ssalonen commented
Rebased now (there were merge conflict), addressed code review comments from @J-N-K

2022-11-01 19:05 UTC, J-N-K approved these changes
Thanks

2022-11-01 19:05 UTC, merged