[voice] Add voice commands for register/unregister dialogs and list them
openhab/openhab-core pull request #3459
Opened 2023-03-16 13:19 UTC by GiviMAD

This PR add new cli voice commands for exposing the new register/unregister dialog capability of the voice manager, plus commands for list existing dialog registrations and running dialogs.

Also fixes a command description issue where the parameter "hlis" were documented as interpreters. I think that "hlis" is better as it is sorter, but let me know if there is a preference over "interpreters".

2023-04-14 09:59 UTC, lolodomo requested changes
Code looks good to me except one or two language typo.

2023-04-14 09:59 UTC, lolodomo commented on bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java
> +                buildCommandUsage(SUBCMD_DIALOGS, "lists the running dialog an its audio/voice services"),
typo: running dialog**s** an**d** **their** ...

2023-04-14 09:59 UTC, lolodomo commented on bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java
> +                        "lists the existing dialog registrations and its selected audio/voice services"),
and **their** ?

2023-04-14 11:37 UTC, GiviMAD commented
Thank you for the review. Should I update the documentation for these commands?

2023-04-14 12:02 UTC, lolodomo commented
> Should I update the documentation for these commands?

Yes please, but wait for the merge first.

2023-07-01 10:57 UTC, GiviMAD commented
Hey @openhab/core-maintainers, I saw yesterday the oh release schedule, do you think this change can be merged before the feature freeze?
It allows more visibility over the running dialogs and expose the register/unregister methods added for the v4.
Thank you.

2023-07-02 09:26 UTC, J-N-K approved these changes

2023-07-02 09:26 UTC, kaikreuzer approved these changes
Sure thing! Sorry for the delay.

2023-07-02 09:27 UTC, merged