Code cleanup: Use Java17 features
openhab/openhab-core pull request #3522
Opened 2023-04-04 00:37 UTC by holgerfriedrich

Applied new language features, mainly instanceof pattern matching. Just on most bundles.
Relates to #3508.

2023-04-14 19:02 UTC, holgerfriedrich commented
Sorry, I had to rebase due to merge conflict.

@wborn would you be willing to review this? Just asking because you did the review of #3508 ;-)
 Should I split the PR up in smaller chunks?

2023-04-15 07:51 UTC, wborn commented
Thanks for all the cleanup @holgerfriedrich! :+1: I can have a look at the PR like it is now. :slightly_smiling_face: Because this PR touches a lot of code, it's probably better to only merge it after M2 is released on Sunday.

2023-04-15 08:08 UTC, holgerfriedrich commented
Good approach, thanks.
Is there a place where developers can find the planned release schedule?

2023-04-15 08:22 UTC, wborn commented
Milestones are usually released in the weekend at the beginning of each month. But they can get postponed in case of stability issues or when maintainers are not available.

Patch releases are usually made on demand when there is enough content or some critical issue (like log4j) pops up.

2023-04-16 09:02 UTC, wborn requested changes
It was a big scroll but all the cleanup looks very good to me! :slightly_smiling_face: 
I only have a few minor comments below:

2023-04-16 09:08 UTC, J-N-K commented on bundles/org.openhab.core/src/main/java/org/openhab/core/items/Item.java
> +    default public @Nullable CommandDescription getCommandDescription() {
I would suggest to omit `public`. Methods on interfaces are always public.

2023-04-16 09:16 UTC, wborn commented on bundles/org.openhab.core/src/main/java/org/openhab/core/items/Item.java
> +    default public @Nullable CommandDescription getCommandDescription() {
Yes that's true! Just remove all the `public` modifiers from the interface. :slightly_smiling_face:

2023-04-16 15:41 UTC, holgerfriedrich commented on bundles/org.openhab.core/src/main/java/org/openhab/core/items/Item.java
> +    default public @Nullable CommandDescription getCommandDescription() {
for now just reverted to status before - lets do this together with the missing parts

2023-04-16 16:00 UTC, holgerfriedrich commented
sorrry had to force push to resolve merge conflict with current main (any way better than fetch upstream, rebase upstream/main, push --force?)

2023-04-16 16:41 UTC, wborn approved these changes
LGTM now!

2023-04-16 16:44 UTC, wborn commented
> any way better than fetch upstream, rebase upstream/main, push --force?

Not really, except for using `--force-with-lease` instead, but that's a bit more chars to type. 😉

2023-04-16 19:44 UTC, merged