[voice] Add length limit to TTS handled by cache
openhab/openhab-core pull request #3699
Opened 2023-07-12 11:53 UTC by dalgwen

During the TTS cache development, there was some discussion about adding a boolean to enable / disable cache per request. We didn't keep that because it makes the API complicated.
But time passed and new usages arise, and maybe it now can be discussed, on a new form ?

For example, there is now a ChatGPT binding. It is possible to make some  advanced chat/queries with a LLM. Most of the time, the chat response are lengthy. And so one "discussion" with a LLM can clog the LRU cache and removes older entries worth keeping.

Proposal :
We can use the TTS length as a simple way to differentiate TTS sentences that should be cached, automatically. 
TTS we should cache are those that can be repeated, and they are nearly always pretty short. examples :
"Ok, I'll do that"
"Hello, what can I do for you ?",
"You've got a message"
"Please close the garage door".

On the other side, one can safely assume that long TTS are generated for report of some kind (meteo, chatGPT ?), probably not meant to be repeated. They are also the ones taking the most space in the cache.

I put a 150 default character limit (configurable). To be discussed if the whole idea worth something.

2023-07-14 08:11 UTC, lolodomo approved these changes
LGTM

2023-07-14 08:11 UTC, lolodomo commented
Looks to me like a very good idea.

2023-07-14 17:57 UTC, J-N-K requested changes
In general LGTM. Is the limit in characters? Maybe add that to the description.

2023-07-14 17:57 UTC, J-N-K commented on bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/cache/TTSLRUCacheImpl.java
> +    private long maxTextLengthCacheTTS = 150;
```suggestion
    private long maxTextLengthCacheTTS = DEFAULT_MAX_TEXT_LENGTH_CACHE_TTS;
```

and use that also below

2023-07-14 17:57 UTC, J-N-K commented on bundles/org.openhab.core.voice/src/main/resources/OH-INF/config/voice.xml
> +				storing it. 0 for no limit.</description>
```suggestion
			<description>The maximum length of texts handled by the TTS cache. If exceeded, will pass the text to the TTS without
				storing it. 0 for no limit.</description>
```

2023-07-15 05:49 UTC, dalgwen commented
Thank you both for your reviews !

2023-07-15 05:50 UTC, J-N-K approved these changes
LGTM, thanks

2023-07-15 07:48 UTC, merged