[modbus] reduce log level when modbus slave returns DEVICE_BUSY exception
openhab/openhab-core pull request #3847
Opened 2023-10-16 17:15 UTC by nagisa

This exception is meant to indicate that the request should be retried shortly, essentially, and at least some of the devices I own seem to be busy bees. Thus my logs receive significant spam of this warning.

Since the exception is transient and retrying it is the expected course of action, I think it makes sense to reduce the log level here slightly and only output an error when the retries get exhausted.

2023-10-31 20:07 UTC, J-N-K requested changes

2023-10-31 20:07 UTC, J-N-K commented on bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusManagerImpl.java
> +                        logger.info(
When re-trying is an expected operation, you can reduce that to DEBUG.

2023-12-10 16:33 UTC, lolodomo commented
@nagisa : did you see the review comment?

2023-12-11 00:50 UTC, nagisa commented on bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusManagerImpl.java
> +                        logger.info(
```suggestion
                        logger.debug(
```

2023-12-14 22:49 UTC, lolodomo commented
@J-N-K : you can probably merge this PR now.

2024-04-28 16:04 UTC, J-N-K approved these changes
Thanks! And sorry for letting you wait so long. I didn't see my comments were addressed.

2024-04-28 16:04 UTC, merged