[wip] UsbSerialDiscovery service based on Windows registry
openhab/openhab-core pull request #3934
Opened 2023-12-19 16:26 UTC by andrewfg

This is a new implementation of the UsbSerialDiscovery interface for Windows, which discovers USB devices by reading from the Windows registry.

This may be an alternative, or an extension, to #3930 

Signed-off-by: Andrew Fiddian-Green [software@whitebear.ch](mailto:software@whitebear.ch)

2023-12-19 16:26 UTC, andrewfg commented
@mherwege 4yi

2023-12-19 16:34 UTC, andrewfg commented
@mherwege it will probably fail the Karaf build (as usual) due to missing feature :(

2023-12-24 15:50 UTC, andrewfg commented
@mherwege I added the missing serial port and interface information

2023-12-27 17:43 UTC, andrewfg commented
As https://github.com/openhab/openhab-core/pull/3922 is now merged, this one is also ready for review.

2023-12-30 21:00 UTC, wborn requested changes
This seems useful for Windows users. :+1: 

I only have a few minor comments:

2023-12-31 14:59 UTC, andrewfg commented on bundles/org.openhab.core.config.discovery.usbserial.windowsregistry/src/test/java/org/openhab/core/config/discovery/usbserial/windowsregistry/test/WindowsUsbDiscoveryTests.java
> +        // TODO write tests
Umm. Not yet. I am still trying to figure out how to mock it in a meaningful way. I think the only real test is a live test on an actual (Windows) system with an actual stick plugged in. And I did that test myself already. So a mockito test would be nice-to-have but perhaps not essential. => @wborn WDYT?

2023-12-31 15:04 UTC, andrewfg commented on bundles/org.openhab.core.config.discovery.usbserial.windowsregistry/src/main/java/org/openhab/core/config/discovery/usbserial/windowsregistry/internal/WindowsUsbSerialDiscovery.java
> +        unchanged.stream().forEach(this::announceAddedDevice);
@wborn I will make the changes in this class. But I think there should be analog changes in the class from which I copied the code => do you want me to make those changes in this PR or another?

2023-12-31 15:04 UTC, andrewfg commented on bundles/org.openhab.core.config.discovery.usbserial.windowsregistry/src/main/java/org/openhab/core/config/discovery/usbserial/windowsregistry/internal/WindowsUsbSerialDiscovery.java
> +                this.scanTask = scheduler.scheduleWithFixedDelay(() -> doSingleScan(), 0, scanInterval.toSeconds(),
Ok.

2023-12-31 15:14 UTC, andrewfg commented on bundles/org.openhab.core.config.discovery.usbserial.windowsregistry/src/main/java/org/openhab/core/config/discovery/usbserial/windowsregistry/internal/WindowsUsbSerialDiscovery.java
> +        unchanged.stream().forEach(this::announceAddedDevice);
https://github.com/openhab/openhab-core/blob/2abe4e20ed1133c89afe43179694c8204d3e6e35/bundles/org.openhab.core.config.discovery.usbserial.ser2net/src/main/java/org/openhab/core/config/discovery/usbserial/ser2net/internal/Ser2NetUsbSerialDiscovery.java#L128

2024-01-02 09:44 UTC, wborn commented on bundles/org.openhab.core.config.discovery.usbserial.windowsregistry/src/test/java/org/openhab/core/config/discovery/usbserial/windowsregistry/test/WindowsUsbDiscoveryTests.java
> +        // TODO write tests
You could move all the `com.sun.jna` logic into some helper class. That class could be mocked and then you can easily test the logic in a unit test. If you don't do this you should remove the useless test class.

2024-01-02 09:46 UTC, wborn commented on bundles/org.openhab.core.config.discovery.usbserial.windowsregistry/src/main/java/org/openhab/core/config/discovery/usbserial/windowsregistry/internal/WindowsUsbSerialDiscovery.java
> +        unchanged.stream().forEach(this::announceAddedDevice);
If there aren't many changes you can do it in this PR.

2024-01-07 11:40 UTC, andrewfg commented on bundles/org.openhab.core.config.discovery.usbserial.windowsregistry/src/test/java/org/openhab/core/config/discovery/usbserial/windowsregistry/test/WindowsUsbDiscoveryTests.java
> +        // TODO write tests
I will remove the test case ;)

2024-01-07 12:06 UTC, andrewfg commented
@wborn there is still the question of which UsbSerialDiscovery components should be loaded on which platforms .. I guess the following .. => WDYT? And the next question is how to program the dependencies and karaf stuff .. which is probably beyond my capabilities :(

- ser2net - all platforms
- sysfs - Linux
- windowsregistry - Windows
- javaxusb - all platforms except Linux and Windows

2024-01-09 23:21 UTC, wborn commented
>  I guess the following

Yes that probably makes sense.

> sysfs - Linux

It doesn't use any native dependency which is very convenient because Linux runs on so many platforms. So it will result in fewer issues compared to javaxusb.

> javaxusb - all platforms except Linux and Windows

It uses native libraries and only supports Linux, Windows and macOS. So it probably only makes sense to use it on macOS.

> And the next question is how to program the dependencies and karaf stuff

You may be able to use `<conditional>` for that, see also https://github.com/openhab/openhab-core/pull/3632#issuecomment-1592847775.

2024-01-10 13:30 UTC, andrewfg commented
> may be able to use <conditional> for that

@wborn the following is simply a wild guess idea .. but I would like to have some feedback from more knowledgeable Karaf experts before even attempting to make such a commit.

.. in particular if the `osgi.native.osname~=Windows` is a proper syntax..

```
<feature name="openhab-transport-serial" description="Serial Transport" version="${project.version}">
    <feature>openhab-core-base</feature>

    <requirement>openhab.tp;filter:="(feature=commons-net)"</requirement>
    <feature dependency="true">openhab.tp-commons-net</feature>

    <requirement>openhab.tp;filter:="(&amp;(feature=serial)(impl=rxtx))"</requirement>
    <feature dependency="true">openhab.tp-serial-rxtx</feature>

    <feature dependency="true">openhab-core-io-transport-mdns</feature>

    <bundle>mvn:org.openhab.core.bundles/org.openhab.core.config.serial/${project.version}</bundle>
    <bundle>mvn:org.openhab.core.bundles/org.openhab.core.config.discovery.usbserial/${project.version}</bundle>
    
    <conditional>
        <condition>req:osgi.native;filter:="(osgi.native.osname=MacOS)"</condition>
        <bundle>mvn:org.openhab.core.bundles/org.openhab.core.config.discovery.usbserial.javaxusb/${project.version}</bundle>
    </conditional>
    
    <conditional>
        <condition>req:osgi.native;filter:="(osgi.native.osname=Linux)"</condition>
        <bundle>mvn:org.openhab.core.bundles/org.openhab.core.config.discovery.usbserial.linuxsysfs/${project.version}</bundle>
    </conditional>
    
    <bundle>mvn:org.openhab.core.bundles/org.openhab.core.config.discovery.usbserial.ser2net/${project.version}</bundle>
    
    <conditional>
        <condition>req:osgi.native;filter:="(osgi.native.osname~=Windows)"</condition>
        <bundle>mvn:org.openhab.core.bundles/org.openhab.core.config.discovery.usbserial.windowsregistry/${project.version}</bundle>
    </conditional>
    
    <bundle>mvn:org.openhab.core.bundles/org.openhab.core.io.transport.serial/${project.version}</bundle>
    <bundle>mvn:org.openhab.core.bundles/org.openhab.core.io.transport.serial.rxtx/${project.version}</bundle>
    <bundle>mvn:org.openhab.core.bundles/org.openhab.core.io.transport.serial.rxtx.rfc2217/${project.version}</bundle>

</feature>
```

2024-01-10 21:21 UTC, wborn commented
I haven't this myself yet. Just give it a try and see what happens. :slightly_smiling_face:

2024-01-10 22:58 UTC, andrewfg commented
> Just give it a try and see what happens

Yeah. I just ran a full build of OH this afternoon (it takes ages on my machine; I probably need to buy a new one). The build succeeded without error. But I will test it tomorrow.

2024-01-11 13:38 UTC, andrewfg commented
@wborn below is a screenshot in Windows showing that this (Windows) discovery is installed, and the existing (Linux) discovery is not. To be ultra safe we would need to check the opposite case on a Linux machine. However I currently don't have a Linux test machine, so I wonder if you could eventually test it for me?

![image](https://github.com/openhab/openhab-core/assets/893994/42ba6cca-b366-4115-96d7-3c96ffebdfff)

2024-01-11 18:58 UTC, wborn commented
> I wonder if you could eventually test it for me?

I just gave it a test on Ubuntu and the linuxsysfs bundle keeps getting installed while the windowsregistry bundle is not. :+1:

2024-01-11 18:59 UTC, wborn approved these changes
Thanks for the new UsbSerialDiscovery!

2024-01-11 19:00 UTC, merged

2024-01-11 19:12 UTC, andrewfg commented
> gave it a test on Ubuntu and the linuxsysfs bundle keeps getting installed

I also -- finally -- managed to test it on a RasPi3 running Linux and it also shows the correct components loaded..

![image](https://github.com/openhab/openhab-core/assets/893994/beb888ef-512a-4ac4-820d-d90735adedcb)