Thinghandlerservice osgi
openhab/openhab-core pull request #3957
Opened 2023-12-24 14:15 UTC by J-N-K

Supersedes #1941 

Since Connor is no longer available I decided to pick up the PR and enhance it. A very good example why we should go this way is https://github.com/openhab/openhab-addons/pull/16037. It implements a `TheKeyTranslationProvider.java` just to pass it from the handler factory to the thing handler and then to the `ThinghandlerService` for localization of the discovery results. There is already similar code in the repository. This is only necessary because we can't inject OSGi services directly to the discovery services.

I started with two implementations in openhab-addons and would like to hear comments from @openhab/core-maintainers before I start a bigger refactoring in openhab-addons.

2023-12-28 11:10 UTC, wborn commented
Thanks for picking it up! It looks good to me so far. :+1: 
Would be nice to get rid of all the workarounds being used for this in the add-ons code. :slightly_smiling_face:

2023-12-31 11:33 UTC, J-N-K commented
@wborn @kaikreuzer I would like to see this merged "soon", because the corresponding PR in openhab-addons will create a lot of merge conflicts each time something is changed in a discovery service. I'll now create a PR for the documentation how to do thing discovery right.

2024-01-01 16:15 UTC, kaikreuzer approved these changes
Thanks for picking this up! Lgtm as far as I can tell.
I leave it to @wborn to have another look and merge it, if he is happy with it.

2024-01-02 11:19 UTC, wborn requested changes
LGTM except for these few minor comments:

2024-01-02 11:19 UTC, wborn commented on bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractThingHandlerDiscoveryService.java
> +    public AbstractThingHandlerDiscoveryService(Class<T> thingClazz, @Nullable Set<ThingTypeUID> supportedThingTypes,
Abstract classes should not have public constructors. Constructors of abstract classes can only be called in constructors of their subclasses. So there is no point in making them public. The protected modifier should be enough.

```suggestion
    protected AbstractThingHandlerDiscoveryService(Class<T> thingClazz, @Nullable Set<ThingTypeUID> supportedThingTypes,
```

2024-01-02 11:19 UTC, wborn commented on bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractThingHandlerDiscoveryService.java
> +    public AbstractThingHandlerDiscoveryService(Class<T> thingClazz, @Nullable Set<ThingTypeUID> supportedThingTypes,
```suggestion
    protected AbstractThingHandlerDiscoveryService(Class<T> thingClazz, @Nullable Set<ThingTypeUID> supportedThingTypes,
```

2024-01-02 11:19 UTC, wborn commented on bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractThingHandlerDiscoveryService.java
> +    public AbstractThingHandlerDiscoveryService(Class<T> thingClazz, int timeout) throws IllegalArgumentException {
```suggestion
    protected AbstractThingHandlerDiscoveryService(Class<T> thingClazz, int timeout) throws IllegalArgumentException {
```

2024-01-02 11:19 UTC, wborn commented on bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractThingHandlerDiscoveryService.java
> +                logger.debug("Background discovery for discovery service '{}' enabled.", this.getClass().getName());
```suggestion
                logger.debug("Background discovery for discovery service '{}' enabled.", getClass().getName());
```

2024-01-02 11:19 UTC, wborn commented on bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractThingHandlerDiscoveryService.java
> +            logger.debug("Background discovery for discovery service '{}' enabled.", this.getClass().getName());
```suggestion
            logger.debug("Background discovery for discovery service '{}' enabled.", getClass().getName());
```

2024-01-02 11:19 UTC, wborn commented on bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandlerFactory.java
> +    private static final String THING_HANDER_SERVICE_CANONICAL_NAME = ThingHandlerService.class.getCanonicalName();
```suggestion
    private static final String THING_HANDLER_SERVICE_CANONICAL_NAME = ThingHandlerService.class.getCanonicalName();
```

2024-01-02 11:19 UTC, wborn commented on bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandlerFactory.java
> +
```suggestion
```

2024-01-02 11:19 UTC, wborn commented on bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandlerFactory.java
> +            this.serviceInstance.initialize();
```suggestion
            serviceInstance.setThingHandler(handler);
            if (serviceNames.length > 0) {
                ServiceRegistration<?> serviceReg = bundleContext.registerService(serviceNames, serviceInstance, null);
                if (serviceReg != null) {
                    this.serviceRegistration = serviceReg;
                }
            }
            serviceInstance.initialize();
```

2024-01-02 11:19 UTC, wborn commented on bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandlerFactory.java
> +            }
```suggestion
            serviceInstance.dispose();

            ServiceRegistration<?> serviceReg = this.serviceRegistration;
            if (serviceReg != null) {
                serviceReg.unregister();
            }

            ServiceObjects<T> serviceObjs = this.serviceObjects;
            if (serviceObjs != null) {
                serviceObjs.ungetService(serviceInstance);
            }
```

2024-01-02 11:40 UTC, J-N-K commented
Done

2024-01-02 12:09 UTC, wborn approved these changes
Thank you!

2024-01-02 12:09 UTC, merged

2024-01-03 12:51 UTC, lolodomo commented
Thank you @J-N-K , I will adjust the openweathermap binding to take benefit of this new feature.

Just one question: what will happen for non official bindings already using ThingHandlerService, will they be broken ?

2024-01-03 12:51 UTC, J-N-K commented
They need to be adjusted accordingly.

2024-01-03 12:54 UTC, lolodomo commented
> They need to be adjusted accordingly.

So something to clearly announce when releasing version 4.2...