[audio|voice] Add console commands to troubleshot audio sources and speech-to-text services.
openhab/openhab-core pull request #4202
Opened 2024-04-28 21:46 UTC by GiviMAD

I would like add these new console commands to allow testing the audio sources and audio transcription capabilities.

Recently I was mentioned at https://community.openhab.org/t/problems-with-dialog-processing-with-pulseaudiobinding/155573 asking for help about these matters and it's difficult to give support about remote setups, so I though that having these commands can help users to troubleshot problems with the audio input and the transcription add-ons.

The new commands are:

### Voice Transcribe

Transcribe audio from default source, optionally specify a different source/file, speech-to-text service or locale.

#### Signature
```sh
voice transcribe [--source <source>]|[--file <file>] [<sttId>] [<locale>]
```
#### Example run:

```sh
openhab> voice transcribe --file turn_on_light.wav
Transcription: turn on light.
```

### Audio Record

Record a wav file of the specified seconds to the sounds folder.

#### Signature

```sh
audio record  [<source>] <seconds> <filename>
````

#### Example run:

```sh
openhab> audio record pulseaudio:source:df54bf45b3:Jabra_Speak2_40_Echo_Cancel_Source 5 turn_on_light
Record done.
```

2024-05-01 00:24 UTC, holgerfriedrich requested changes
Thank you!
Find a few suggestions regarding wording below, otherwise LGTM.

Would you mind creating a PR in the documentation repo?
I think it should be documented here:
https://github.com/openhab/openhab-docs/blob/main/configuration/multimedia.md

2024-05-01 00:24 UTC, holgerfriedrich commented on bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java
> +                buildCommandUsage(SUBCMD_SAY + " <text>", "speaks a text"),
this seems to be duplicate (see line 101)

2024-05-01 00:24 UTC, holgerfriedrich commented on bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java
> +            console.println("No transcription generated.");
```suggestion
            console.println("No transcription generated");
```

2024-05-12 10:08 UTC, GiviMAD commented
I have to make a last moment commit to address an error on the transcribe description I saw while creating the docs PR.

Thank you for the review!

2024-05-12 10:25 UTC, holgerfriedrich approved these changes
LGTM, thank you

2024-05-12 10:25 UTC, merged