[voice] Skip say recognition error
openhab/openhab-core pull request #4278
Opened 2024-06-22 15:28 UTC by GiviMAD

I would like to add this fix to the dialog processor, which avoid playing the content of the SpeechRecognitionErrorEvent unless it's explicitly indicated on it.

I think is more friendly to just fail and don't continue the dialog than to "speak" a text that can be a forwarded exception message, so I changed the log for the SpeechRecognitionErrorEvent and added the "notify" field on the SpeechRecognitionErrorEvent class which is false by default.

2024-06-22 15:36 UTC, GiviMAD commented
@lolodomo, if you can give me your opinion on these changes, It's related to the review comment https://github.com/openhab/openhab-addons/pull/15166#discussion_r1645487632

2024-06-22 18:31 UTC, lolodomo requested changes
With these changes, you remove the "saying" of the error message with all the existing SST services. Is it really a good idea to say nothing ?

2024-06-22 18:31 UTC, lolodomo commented on bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/SpeechRecognitionErrorEvent.java
> +    public Boolean getNotify() {
boolean rather than Boolean

2024-06-22 19:38 UTC, GiviMAD commented
> With these changes, you remove the "saying" of the error message with all the existing SST services. Is it really a good idea to say nothing ?

I'm not sure about it, I remember to have an issue with an exception message coming through the speaker, and I think that is something that shouldn't happen, but maybe it's more correct to fix that on the specific binding instead of changing the behavior.

But I think that in some cases like for an empty transcription, you don't want to say anything, because it's probably the result of an incorrect spot event and better to not introduce extra noise telling something and disturb the user, other systems seem to work like that.

I can set notify to true by default if you think is a better idea.

2024-06-23 08:05 UTC, lolodomo commented
As I suggested in my last comment in the review of the whisper STT service, why not letting the user decide if he wants or not a spoken feedback ? If the message is blank, nothing is said. WDYT ?

2024-06-23 08:11 UTC, lolodomo commented on bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java
> +                    say(text == null ? sre.getMessage() : text.replace("{0}", sre.getMessage()));
Maybe your problem was the injection of the message coming from `SpeechRecognitionErrorEvent`  inside a more global message defined by the entry "error.stt-error" ?
Maybe you should say simply the message coming from `SpeechRecognitionErrorEvent` ?

2024-06-23 11:35 UTC, lolodomo commented on bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java
> +                }
In that case, the message "error.stt-error" is never used and can be removed.

Please also check that all existing STT services are appropriate with this change.

2024-06-23 14:32 UTC, lolodomo approved these changes
LGTM

2024-06-23 21:04 UTC, kaikreuzer approved these changes
Thanks for the review, @lolodomo.

2024-06-23 21:06 UTC, merged