Extend Stringutils with padRight
openhab/openhab-core pull request #4279
Opened 2024-06-23 12:36 UTC by lsiepel

Earlier some string utils where added to core in order to remove the dependency on `org.apache.commons.lang3.StringUtils`.
While doing so i create a `padLeft`, but forgot a `padRight` method. This PR corrects that.

2024-06-23 16:38 UTC, J-N-K requested changes

2024-06-23 16:38 UTC, J-N-K commented on bundles/org.openhab.core/src/main/java/org/openhab/core/util/StringUtils.java
> +        String paddedString = str == null ? "" : str;
```suggestion
        String paddedString = Objects.requireNonNullElse(str, "");
```

2024-06-23 17:52 UTC, holgerfriedrich reviewed
I hope I do not get this wrong, but I there are two observations (for edge cases):
- It seems you replace all occurrences of ```" "``` in the original String as well.
- You replace a single character ```" "``` possibly by a multi-character String, which might result in the String to be longer than minSize.

Both might be unexpected for the user.

2024-06-23 18:06 UTC, lsiepel commented on bundles/org.openhab.core/src/main/java/org/openhab/core/util/StringUtils.java
> +        String paddedString = str == null ? "" : str;
Fixed

2024-06-23 19:03 UTC, lsiepel commented
> I hope I do not get this wrong, but I think there are two observations (for edge cases):
> 
> * It seems you replace all occurrences of `" "` in the original String as well.
> * You replace a single character `" "` possibly by a multi-character String, which might result in the String to be longer than minSize.
> 
> Both might be unexpected for the user.

Agree that might be unexpected, i just changed the implementation a bit, support for strings with whitespaces is added now.

2024-06-23 21:49 UTC, holgerfriedrich approved these changes
LGTM, thanks

2024-06-24 17:48 UTC, J-N-K approved these changes
Thanks!

2024-06-24 19:06 UTC, merged