Fix parsing of mac address in SDDP Discovery
openhab/openhab-core pull request #4284
Opened 2024-06-30 02:34 UTC by mlobstein

Fix issue reported by: https://github.com/openhab/openhab-addons/issues/16964

If the SDDP host address field contains colons in the mac address, remove them.

@andrewfg @lolodomo

2024-06-30 05:04 UTC, holgerfriedrich requested changes

2024-06-30 05:04 UTC, holgerfriedrich commented on bundles/org.openhab.core.config.discovery.sddp/src/main/java/org/openhab/core/config/discovery/sddp/SddpDevice.java
> +                : hostParts[hostParts.length - 1].replaceAll(":", "").replaceAll("(..)(?!$)", "$1-").toLowerCase();
```suggestion
                : hostParts[hostParts.length - 1].replace(":", "").replaceAll("(..)(?!$)", "$1-").toLowerCase();
```
No regex needed, ```replace``` should be more efficient.

2024-06-30 07:05 UTC, andrewfg requested changes
@mlobstein thanks for this. However since mac addresses can be delimited by either colon or dash characters, I would suggest to replace both of them as follows..

```
        macAddress = hostParts.length <= 1 ? ""
                : hostParts[hostParts.length - 1].replaceAll("[-:]", "").replaceAll("(..)(?!$)", "$1-").toLowerCase();
```

2024-06-30 07:09 UTC, andrewfg requested changes

2024-06-30 07:09 UTC, andrewfg commented on bundles/org.openhab.core.config.discovery.sddp/src/main/java/org/openhab/core/config/discovery/sddp/SddpDevice.java
>       * Note: the last 12 characters represent the MAC address of the device.
.. the last 12 resp. 17 characters represent..

2024-06-30 10:14 UTC, andrewfg commented
> since mac addresses can be delimited by either colon or dash characters

HOWEVER the Host header is being split on underscore or dash characters, so a Mac address delimited on dashes would in fact fail for other reasons. So actually I would approve @holgerfriedrich 's proposed version. :)

2024-06-30 12:57 UTC, mlobstein commented
Changes pushed, however the build is failing for unrelated reasons.

2024-06-30 13:13 UTC, andrewfg approved these changes
LGTM and thanks for updating the JUnit test too.

2024-06-30 13:28 UTC, holgerfriedrich approved these changes
LGTM, thanks!

2024-07-01 14:31 UTC, mlobstein commented
@wborn @holgerfriedrich please merge before the final build of OH 4.2.0 if possible.

2024-07-01 15:56 UTC, merged