Upgrade to JmDNS 3.5.11
openhab/openhab-core pull request #4337
Opened 2024-08-07 13:28 UTC by kaikreuzer

See [changelog 3.5.10](https://github.com/jmdns/jmdns/releases/tag/3.5.10) (and [changelog 3.5.11](https://github.com/jmdns/jmdns/releases/tag/3.5.11))

2024-08-07 15:43 UTC, wborn requested changes
I think the Karaf feature still needs to be updated.

2024-08-08 09:13 UTC, kaikreuzer commented
Hm, I thought I did it this time, but it is indeed missing in the commit...
Anyhow, let's wait with the merge until https://github.com/jmdns/jmdns/issues/281 is clarified.

2024-08-28 19:31 UTC, holgerfriedrich requested changes
Ready to switch to 3.5.12?

2024-08-28 19:31 UTC, holgerfriedrich commented on bom/compile/pom.xml
> +      <version>3.5.11</version>
```suggestion
      <version>3.5.12</version>
```

2024-08-28 19:31 UTC, holgerfriedrich commented on bom/runtime/pom.xml
> +      <version>3.5.11</version>
```suggestion
      <version>3.5.12</version>
```

2024-08-28 19:31 UTC, holgerfriedrich commented on features/karaf/openhab-tp/src/main/feature/feature.xml
> +		<bundle>mvn:org.jmdns/jmdns/3.5.11</bundle>
```suggestion
		<capability>openhab.tp;feature=jmdns;version=3.5.12</capability>
		<bundle>mvn:org.jmdns/jmdns/3.5.12</bundle>
```

2024-08-28 19:31 UTC, holgerfriedrich commented on itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
> +	javax.jmdns;version='[3.5.11,3.5.12)',\
```suggestion
	javax.jmdns;version='[3.5.12,3.5.13)',\
```

2024-08-29 20:23 UTC, kaikreuzer commented
> Ready to switch to 3.5.12?

For sure!
But to be on the safe side, I would suggest waiting with merging it until after 4.3.0.M1.

2024-08-29 21:10 UTC, holgerfriedrich approved these changes
LGTM

2024-09-06 21:19 UTC, holgerfriedrich commented
@wborn I think your review comment has been addressed, can we merge?

2024-09-07 07:20 UTC, wborn approved these changes
Thank you both!

2024-09-07 07:21 UTC, merged