Add MEDIAN group function
openhab/openhab-core pull request #4344
Opened 2024-08-11 14:46 UTC by jimtng

Resolve #4341

2024-08-11 15:37 UTC, J-N-K requested changes
Otherwise LGTM. Thanks!

2024-08-11 15:37 UTC, J-N-K commented on bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunction.java
> +                        .sorted((s1, s2) -> s1.compareTo(s2)).collect(Collectors.toList());
```suggestion
                        .sorted((s1, s2) -> s1.compareTo(s2)).toList();
```

2024-08-11 15:37 UTC, J-N-K commented on bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/ArithmeticGroupFunction.java
> +                        .filter(Objects::nonNull).sorted((s1, s2) -> s1.compareTo(s2)).collect(Collectors.toList());
```suggestion
                        .filter(Objects::nonNull).sorted((s1, s2) -> s1.compareTo(s2)).toList();
```

2024-08-11 21:38 UTC, mherwege commented
@jimtng Great you took this one. I am wondering if it makes sense to use a more performant algorithm using heaps? See https://www.baeldung.com/java-stream-integers-median-using-heap. I expect it will for the other case with persistence when looking at a longer period with many data points. Here the impact could be important because this recalculation (and sorting) will ve done for every state change of an item in the group.

2024-08-11 22:07 UTC, mherwege commented
And here is a text on another, at first side even better, algorithm: https://rcoh.me/posts/linear-time-median-finding/

2024-08-12 05:16 UTC, jimtng commented
@mherwege great idea! I'm going to do some tests comparing the two/three implementations. 

I'm also wondering about keeping an in-memory sorted list and update it whenever the members changed. That would involve a sorting operation at the beginning, and only deletion + insertion of (changed|added|removed) item(s), which should probably be even faster than any quickselect / heap median algorithm. However, the way it's currently done, we got given a list of items with no knowledge of the groupitem (only the baseitem). So to do that, a lot of things would need to be changed.

2024-08-12 06:05 UTC, mherwege commented
@jimtng I am not sure the extra complexity of handling item state changes + item addition + item removal in a group are worth it for this use case. Using an algorithm that scales linearly (or at least most of the time) with number of items I suspect does.
Looking at the algorithms, the advantage of the heap methods is when you want to have a stream of medians with every item you add. It avoids sorting (or quickselect) every time. That is not the case here. You only need to calculate once for a change every time, so quickselect looks like the most promising. I of course applaud you intending to test it.

2024-08-12 06:06 UTC, mherwege commented
> deletion + insertion of (changed|added|removed) item(s)

That’s what the heap approach could optimise.

2024-08-14 11:48 UTC, jimtng commented
Note: waiting for #4345 to be merged, and refactor to use the `Statistics.median` method.

2024-08-24 10:16 UTC, mherwege commented
@jimtng https://github.com/openhab/openhab-core/pull/4345 has been merged.

2024-08-24 11:03 UTC, jimtng commented
Thanks, updated!

2024-08-24 12:39 UTC, J-N-K approved these changes
LGTM

2024-08-24 12:39 UTC, merged