Support channel transformations with parentheses
openhab/openhab-core pull request #4352
Opened 2024-08-18 13:00 UTC by jimtng

Support both `JSONPATH:$.xx` and `JSONPATH($.xx)` syntaxes.

The aim is to make transformation pattern uniform between bindings and core, e.g. in item / sitemap labels, so we can just use the parentheses everywhere. Perhaps colon syntax can be phased out eventually but for now they're both supported to maintain compatibility.

2024-08-18 13:17 UTC, J-N-K requested changes
In general looks good to me. Can you also add a test for the mixed case (i.e. both patterns in one transformation chain)?

2024-08-18 13:24 UTC, jimtng commented
tests for mixed syntax added

2024-08-18 15:05 UTC, J-N-K approved these changes
LGTM, thanks for the improvement

2024-08-18 15:05 UTC, merged

2024-08-20 07:30 UTC, lolodomo commented
I guess something has to be changed in core.ui to support syntax with ":"?
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java#L125

2024-08-20 07:38 UTC, jimtng commented
At the moment this class is used just for addons. I am looking through the core code to see if we can apply a common code to handle all transformation related tasks, so that they will all support chaining and perhaps also support `:`.