IP addon finder mac address format tweak
openhab/openhab-core pull request #4481
Opened 2024-12-08 13:30 UTC by andrewfg

Tweaks to #4477

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

2024-12-08 13:32 UTC, andrewfg commented
@holgerfriedrich ping!!

2024-12-09 20:31 UTC, holgerfriedrich commented
@andrewfg Sorry, I did not manage to review this before Kai pressed the button to build M5. Shouldn't be a problem to delay this, as the merged implementation works for the common delimiters.

2024-12-09 21:20 UTC, andrewfg commented
Yes. It really only affects developers who might write faulty code. And probably such developers will be using snapshots anyway.

2025-01-24 17:15 UTC, andrewfg commented
@holgerfriedrich this is ready to merge.

2025-01-26 16:42 UTC, holgerfriedrich requested changes
@andrewfg I am sorry for keeping you waiting so long.
Could you please fix the SAT warning? I will check again soon, promised.

2025-01-26 16:42 UTC, holgerfriedrich commented on bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java
> +     *
This empty line seems to cause a new SAT warning, 
```
checkstyle | 3 | 619 | style | JavadocMethodStyleCheck | There should be no empty lines between tags in a Javadoc comment of a method or constructor.
```

```suggestion
```

2025-01-26 16:42 UTC, holgerfriedrich commented on bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java
> +        return false;
Could you pls add a comment what this part of the method is trying to achieve?

Actually, it took me some time to get what you are trying to do (hopefully I got it correctly): 
* When there is no letter in the format string -> index will be last +1, switch will not hit a case -> false
* When there exactly one letter as last char of the format string -> the loop breaks at index=last -> switch case 0, true
* else if the letter is the 2nd last character -> break, switch will hit case "1" -> true if last char is a special character (!=letter/digit)
* else false....

seems to be the right thing... a regex-like description could be "[number]*[letter][!letterdigit]?" (this is not a proposal to use regex, comment would be sufficient)

2025-01-27 10:40 UTC, andrewfg commented on bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java
> +     *
Removed

2025-01-27 21:47 UTC, holgerfriedrich approved these changes
LGTM, thanks!

2025-01-27 21:48 UTC, merged