Another warning hunting session
openhab/openhab-core pull request #4484
Opened 2024-12-09 09:52 UTC by clinique

Focused on "Potential null pointer access"

2025-01-01 22:29 UTC, holgerfriedrich requested changes
Thanks!
I left a few comments.
For the computation of hash codes, `Objects.hashCode` could be helpful, as it handles the `null` values properly.

2025-01-02 14:28 UTC, clinique commented on bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/PeriodicAdjuster.java
> +        Temporal nextTime = Objects.requireNonNull(timeDone).plus(current);
In the current design, we would create an NPE if timeDone is null and temporal is null also. I can't imagine this is the expected behavior of this method and as I do not get clearly what was the strategy of this design, I'll revert this change.

2025-01-02 14:45 UTC, clinique commented on bundles/org.openhab.core/src/main/java/org/openhab/core/types/StateOption.java
> +        result = prime * result + (label instanceof String string ? string.hashCode() : 0);
Changed

2025-01-02 18:04 UTC, holgerfriedrich reviewed
I would actually prefer `Objects.hashCode()` over `Objects.hash()`....
Using `hash()` will change the value, compared to what we had before:
https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Objects.html#hash(java.lang.Object...)
(not sure if this is relevant for this class, but we might run into trouble with persisted data)

2025-01-03 07:59 UTC, clinique commented
> I would actually prefer `Objects.hashCode()` over `Objects.hash()`.... Using `hash()` will change the value, compared to what we had before: https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Objects.html#hash(java.lang.Object...) (not sure if this is relevant for this class, but we might run into trouble with persisted data)

Done @holgerfriedrich

2025-01-03 17:47 UTC, holgerfriedrich commented on bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java
> +            list.add(directoryChangeEvent);
This is less readable and I would prefer to roll it back for now. I am fine will all other changes and would prefer to merge first.

2025-01-06 11:04 UTC, clinique commented on bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java
> +            list.add(directoryChangeEvent);
@holgerfriedrich : done

2025-01-06 17:49 UTC, merged