Some non null annotations
openhab/openhab-core pull request #4486
Opened 2024-12-09 10:47 UTC by clinique

2025-01-15 21:59 UTC, holgerfriedrich requested changes

2025-01-15 21:59 UTC, holgerfriedrich commented on bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/LanguageResourceBundleManager.java
> +    private @Nullable String getTranslatedText(String resourceName, String key, Locale locale) {
The parameters may be `Nullable` as well. According to the [docs](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/ResourceBundle.html#getBundle(java.lang.String,java.util.Locale,java.lang.ClassLoader,java.util.ResourceBundle.Control)), it would cause a NullpointerException in `getBundle`, which leads to returning null.

Not sure if this is the way to go, but at least it would be more consistent with the other methods above.

2025-01-16 13:23 UTC, clinique commented on bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/BundleResolverImpl.java
>      @Override
Correct. Changed.

2025-01-16 13:24 UTC, clinique commented on bundles/org.openhab.core/src/main/java/org/openhab/core/util/BundleResolver.java
>      /**
Done.

2025-01-19 10:30 UTC, wborn commented on bundles/org.openhab.core/src/main/java/org/openhab/core/items/RegistryHook.java
>  public interface RegistryHook<E extends Identifiable<?>> {
Looks like it was only used by the `ChannelItemProvider` (https://github.com/eclipse-archived/smarthome/pull/4580) which got removed when the simple linking mode was removed with https://github.com/openhab/openhab-core/pull/1643. So removing this unused functionality in 5.0 makes sense to me.

There also seems to be still some code referring to the  `ChannelItemProvider`: 
https://github.com/search?q=repo%3Aopenhab%2Fopenhab-core+ChannelItemProvider&type=code

2025-01-19 10:44 UTC, holgerfriedrich commented on bundles/org.openhab.core/src/main/java/org/openhab/core/items/RegistryHook.java
>  public interface RegistryHook<E extends Identifiable<?>> {
Thanks, I will create a separate PR.
The reference to `ChannelItemProvider` in the suppression list is removed in #4555.
I will create another PR to remove `RegistryHook` and have look at the test you just mentioned.

2025-01-19 22:12 UTC, holgerfriedrich commented on bundles/org.openhab.core/src/main/java/org/openhab/core/items/RegistryHook.java
>  public interface RegistryHook<E extends Identifiable<?>> {
#4568 and openhab/openhab-addons#18134

2025-02-02 15:31 UTC, holgerfriedrich approved these changes
LGTM, thanks, and sorry for the long delay

2025-02-02 15:32 UTC, holgerfriedrich commented
@clinique could you pls. rebase? RegistryHook was deleted in the meantime.

2025-02-03 19:38 UTC, holgerfriedrich approved these changes

2025-02-03 20:45 UTC, holgerfriedrich commented
...almost there.
What is missing is just the update of four itests which now break the build

```     private class BundleResolverImpl implements BundleResolver {
         @Override
+        @Nullable
         public Bundle resolveBundle(@Nullable Class<?> clazz) {
```

2025-02-05 06:52 UTC, holgerfriedrich commented on bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/LanguageResourceBundleManager.java
> +            } catch (NullPointerException ex) {
```suggestion
            } catch (NullPointerException | IllegalArgumentException | MissingResourceException ex) {
```

2025-02-05 21:02 UTC, holgerfriedrich commented
Good, the CI is completing.
I checked if compiling the addons repo still works, actually 3 bindings fail to compile. PR is already there, see openhab/openhab-addons#18231.

It also requires 2 more changes in this PR, could you pls. add `@Nullable` to the parameter `bundle` of to the following methods?
`ProfileTypeI18nLocalizationService.java`: `createLocalizedProfileType(@Nullable Bundle bundle` and
`ProfileI18nUtil.java`: `getProfileLabel(@Nullable Bundle bundle`?

2025-02-09 13:55 UTC, holgerfriedrich approved these changes
LGTM.
Thank you for following up on this and your patience to go through many iterations!

2025-02-09 13:55 UTC, merged